Repository hmcts/pip-subscription-management, pull requests merged in 2022-10, with the labels that each got.

#84 PUB-1564 Spring Updates
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/config/OpenApiConfiguration.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/RootController.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionController.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/Subscription.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/SubscriptionDto.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/pip/subscription/management/config/SwaggerConfigurationTest.java
Labels: ns:pip, prd:pip, rel:pip-subscription-management-pr-84

#85 Updated dependency
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:pip, prd:pip, rel:pip-subscription-management-pr-85

#87 Added dependabot
  .github/dependabot.yml
Labels: ns:pip, prd:pip, rel:pip-subscription-management-pr-87
