Repository hmcts/pip-subscription-management, pull requests merged in 2023-06, with the labels that each got.

#233 PUB-1996 - Updated chart + dependencies
  README.md
  build.gradle
  charts/pip-subscription-management/Chart.yaml
  config/owasp/suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/reform/pip/subscription/management/config/SwaggerPublisherTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/pip/subscription/management/config/WebClientConfigurationTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/GetWelcomeTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/MetadataControllerTests.java
  src/functionalTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionControllerTests.java
  src/functionalTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/ViewControllerTests.java
  src/functionalTest/resources/application-functional.yaml
  src/functionalTest/resources/mock/artefact.json
Labels: ns:pip, prd:pip, rel:pip-subscription-management-pr-233

#235 PUB-1900 update Gradle to V8
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: ns:pip, prd:pip, rel:pip-subscription-management-pr-235

#237 Suppress CVE-2023-35116
  config/owasp/suppressions.xml
Labels: ns:pip, prd:pip, rel:pip-subscription-management-pr-237
