Repository hmcts/pip-subscription-management, pull requests merged in 2023-04, with the labels that each got.

#193 PUB-1693 Move shared model classes to pip-data-models
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/MetadataControllerTests.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionControllerTests.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/authentication/roles/IsAdmin.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/MetadataController.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionController.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/ViewController.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/Channel.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/SearchType.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/Subscription.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/SubscriptionDto.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/external/account/management/AzureAccount.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/external/account/management/PiUser.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/external/account/management/Roles.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/external/account/management/UserProvenances.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/external/data/management/Artefact.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/external/data/management/ArtefactType.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/external/data/management/Language.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/external/data/management/ListType.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/external/data/management/Sensitivity.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/external/publication/services/LocationSubscriptionDeletion.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/external/publication/services/ThirdPartySubscription.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/external/publication/services/ThirdPartySubscriptionArtefact.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/response/ListTypeSubscription.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/subscriptionmanagement/Location.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/AccountManagementService.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/DataManagementService.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/MetadataService.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/PublicationServicesService.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionLocationService.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionNotificationService.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionService.java
  src/test/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/MetadataControllerTest.java
  src/test/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionControllerTest.java
  src/test/java/uk/gov/hmcts/reform/pip/subscription/management/errorhandling/GlobalExceptionHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/pip/subscription/management/helpers/SubscriptionUtils.java
  src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/AccountManagementServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/ChannelManagementServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/MetadataServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/PublicationServicesServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionLocationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/UserSubscriptionServiceTest.java
Labels: ns:pip, prd:pip, rel:pip-subscription-management-pr-193

#207 PUB-1991 - Formatting change
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-subscription-management-pr-207

#210 Update spring boot version to fix CVE-2023-20863
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-subscription-management-pr-210
