Repository hmcts/pip-subscription-management, pull requests merged in 2024-06, with the labels that each got.

#357 Updated providers
  infrastructure/providers.tf
Labels: ns:pip, prd:pip, stg/add-or-update, prod/add-or-update, rel:pip-subscription-management-pr-357

#351 PUB-2471 - Batch send subscriptions to Publication Services
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/BulkSubscriptionsSummary.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/SubscriptionsSummary.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/PublicationServicesService.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionNotificationService.java
  src/test/java/uk/gov/hmcts/reform/pip/subscription/management/models/BulkSubscriptionsSummaryTest.java
  src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/PublicationServicesServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionNotificationServiceTest.java
Labels: ns:pip, prd:pip, rel:pip-subscription-management-pr-351

#353 PUB-2363 - Update Data Models version number
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-subscription-management-pr-353

#352 PUB-2454 - Update pip-data-models with new list type IAC Daily Cause …
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-subscription-management-pr-352

#359 PUB-2490 - Updated jenkins nightly time
  Jenkinsfile_nightly
  config/owasp/suppressions.xml
Labels: ns:pip, prd:pip, rel:pip-subscription-management-pr-359
