Repository hmcts/pip-subscription-management, pull requests merged in 2024-03, with the labels that each got.

#334 PUB-2121 Update pip-data-models version
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-subscription-management-pr-334

#340 PUB-2281 - Remove trailing slash parameter
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/config/WebConfiguration.java
Labels: ns:pip, prd:pip, rel:pip-subscription-management-pr-340

#339 PUB -2334 Dependency updates
  build.gradle
  config/owasp/suppressions.xml
  infrastructure/.terraform-version
  infrastructure/providers.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-subscription-management-pr-339
