Repository hmcts/pip-subscription-management, pull requests merged in 2025-01, with the labels that each got.

#387 PUB-2693 - Updated Dependencies
  build.gradle
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  infrastructure/.terraform-version
  infrastructure/providers.tf
  src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/TestingSupportControllerTests.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/utils/IntegrationBasicTestBase.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/PublicationServicesServiceTest.java
Labels: ns:pip, prd:pip, stg/add-or-update, prod/add-or-update, rel:pip-subscription-management-pr-387

#386 PUB-2706 - Non Strategic Publishing
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-subscription-management-pr-386

#383 PUB-2588 Add list type subscription and functional tests for Subscription Controller
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/pip/subscription/management/SubscriptionTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/pip/subscription/management/utils/FunctionalTestBase.java
  src/functionalTest/java/uk/gov/hmcts/reform/pip/subscription/management/utils/OAuthClient.java
  src/functionalTest/resources/application-functional.yaml
  src/functionalTest/resources/subscription/civilDailyCauseList.json
  src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionControllerTests.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/repository/SubscriptionListTypeRepositoryTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/repository/SubscriptionRepositorySearchTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/repository/SubscriptionRepositoryTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/utils/IntegrationBasicTestBase.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionController.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/Subscription.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/SubscriptionListType.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/response/LocationSubscription.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/repository/SubscriptionListTypeRepository.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/repository/SubscriptionRepository.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionLocationService.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionNotificationService.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionService.java
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/UserSubscriptionService.java
  src/main/resources/db/migration/V1.3__create_ist_type_subscription.sql
  src/main/resources/db/migration/V1.4__list_type_subscription.sql
  src/test/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionControllerTest.java
  src/test/java/uk/gov/hmcts/reform/pip/subscription/management/helpers/SubscriptionUtils.java
  src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionLocationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/UserSubscriptionServiceTest.java
Labels: ns:pip, prd:pip, rel:pip-subscription-management-pr-383

#395 PUB-2588 - Update permissions
  infrastructure/tf-db-flexible.tf
Labels: ns:pip, prd:pip

#378 PUB-2674 - Mocked external calls for subscription management
  Jenkinsfile_CNP
  README.md
  src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/config/SwaggerPublisherTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionControllerTests.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/ViewControllerTests.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/repository/SubscriptionRepositorySearchTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/repository/SubscriptionRepositoryTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/utils/IntegrationBasicTestBase.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/utils/IntegrationTestBase.java
  src/integrationTest/resources/application-integration.yaml
  src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionLocationService.java
Labels: ns:pip, prd:pip, rel:pip-subscription-management-pr-378

#396 PUB-2720 Update non strategic list names
  build.gradle
Labels: ns:pip, prd:pip

#394 PUB-2702 Update dependencies
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  infrastructure/.terraform-version
  infrastructure/providers.tf
Labels: ns:pip, prd:pip, stg/add-or-update, prod/add-or-update

#397 PUB-2742 Update and Add UT IAC Lists
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-subscription-management-pr-397
